---

global:
  provider: virtualbox
  cpu: 2
  memory: 1024
vms:
  server:
    autostart: true
    box: inclusivedesign/centos7
    gui: false
    networks:
      private:
        type: private
    folders:
      code:
        src: "."
        dest: "/home/vagrant/sync/node_modules/universal"
  fedora:
    autostart: true
    box: inclusivedesign/fedora24
    gui: true
    sound: true
    cpu: 4
    memory: 2048
    networks:
      private:
        type: private
    folders:
      code:
        src: "."
        dest: "/home/vagrant/sync/node_modules/universal"

